### PR TITLE
Fixed Header Overlay Issue on Smaller Resolutions

### PR DESCRIPTION
**Pull request by shirleyfyx**
- Changed Navbar Positioning from fixed to sticky to ensure the main content doesn't get obscured. 
- Closes https://github.com/waterloo-rocketry/website-react/issues/49

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/50)

### CODE REVIEW

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Now that the top of a bunch of pages isn't behind the navbar, it seems that some pages might have too much space on the top of the page. One good example is the rockets page:


Other pages have not enough space between the navbar and the page heading. Could we lessen/largen these bits of space where needed?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/50#-:-NguX7ap6hfUQ9BflNb6:b-n8tf77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @shirleyfyx)

**Comment by QuantumManiac** [comment]
It also seems that the "sticky" navbar disappears if you scroll down far enough on pages that are long enough, e.g. the Sponsors and Team page. It would be good to have it visible throughout the page

**Comment by shirleyfyx** [comment]
The rocket page is now vertically centred within its container. 
image

**Review by QuantumManiac — APPROVED** [review]
LGTM! Just one fix to the padding that I mentioned and it should be good to go.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/50#-:-NhHqmZj8rtm1HiM2bmA:bwcw0ul)* status: all files reviewed, 1 unresolved discussion (waiting on @shirleyfyx)

___
*[`src/index.css` line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/50#-NhHqDnQ1ywL7kVIschP:-NhHqDnQ1ywL7kVIschQ:b-m38p3j) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0d085cde1af9dd4d581f4b76289cba22733d0fc8/src/index.css#L15)):*
> ```CSS
> body {
>   margin: 0;
>   padding-top: 3.35rem;
> ```

If you take a close look at the pages with banners at the top of the page, you can see that part of the banner still is behind the navbar:


After a bit of testing, I think 4.2rem is the exact height of the navbar

 



_Suggestion:_
```CSS
  padding-top: 4.2rem;
```

**Review by QuantumManiac — APPROVED** [review]
Once the padding is fixed for (hopefully) the last time, you should be good to go!

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/50#-:-NhNuAMi2uSHtm2e-I-0:b705614)* status: all files reviewed, 1 unresolved discussion (waiting on @Darth-Raazi and @shirleyfyx)

___
*[`src/index.css` line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/50#-NhHqDnQ1ywL7kVIschP:-NhNteTk4txGPtNMhiWL:bmea6kq) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0d085cde1af9dd4d581f4b76289cba22733d0fc8/src/index.css#L15)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

If you take a close look at the pages with banners at the top of the page, you can see that part of the banner still is behind the navbar:


After a bit of testing, I think 4.2rem is the exact height of the navbar
</blockquote></details>

I noticed that now the padding is slightly too high. It seems that the actual height of the navbar is 66.7946px i.e. 4.175rem. Please also make sure that this is correct, and remains as such on any resolution.



_Suggestion:_
```CSS
  padding-top: 4.175rem;
```

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/50#-:-NhOy2zpCSbAZ_Jnd9EC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @shirleyfyx)

**Pull request merged**
