### PR TITLE
Completed(?) Team page

### PR DESCRIPTION
**Pull request by Carolx715**
- New component MemberImage
- Lots of member images added
- Text gradient when hovering over image is very cool however I want to verify it works on other devices too :) 
- Also yeah I think i am finished this page but its also very late and i did this all in one sitting so im sure yall have something to say
- By the way, this page is no rush to review. PLEASE review and/or fix the other PRs first :)

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/16)

### CODE REVIEW

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/16)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Carolx715, @Kenttrann2302, and @QuantumManiac)

___
*[`src/routes/Team.jsx` line 94 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/16#-NHBUl8o5bCXVPDqmts8:-NHBUl8o5bCXVPDqmts9:bng39xy) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/715e8b657b10d41d18907468ede2b3c47032378c/src/routes/Team.jsx#L94)):*
> ```JavaScript
>         </Row>
> 
>         <Container className={styles.containerFluid} fluid>
> ```


There is some odd whitespace on the right side 
___
*[`src/routes/Team.jsx` line 117 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/16#-NHBQTAV2e5bzfDo0Vt9:-NHBQTAV2e5bzfDo0VtA:b-ueeb2r) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/715e8b657b10d41d18907468ede2b3c47032378c/src/routes/Team.jsx#L117)):*
> ```JavaScript
>           <MemberImage image={ChrisSankey} name="Chris Sankey" descriptor="Recovery Lead" />
>           <MemberImage image={Saduni} name="Saduni Sumithrarachchige" descriptor="Payload" />
>           <MemberImage image={KavinS} name="Kavin Satheeskumar" descriptor="Software/Payload" />
> ```

Ayo, my mom has been asking me for ages to get this changed to "Software Lead" and remove the title from Wendi, want to be a homie and do that for me?

**Review by Carolx715 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/16)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @KavinSatheeskumar, @Kenttrann2302, and @QuantumManiac)

___
*[`src/routes/Team.jsx` line 94 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/16#-NHBUl8o5bCXVPDqmts8:-NHLW37B-BbEiOuiTKOv:b-ab9lnj) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/715e8b657b10d41d18907468ede2b3c47032378c/src/routes/Team.jsx#L94)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>


There is some odd whitespace on the right side 
</blockquote></details>

What do you think should happen instead of that, should the images be centred? 
___
*[`src/routes/Team.jsx` line 117 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/16#-NHBQTAV2e5bzfDo0Vt9:-NHLW1dr2zRVF00YGcXJ:b2ni78k) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/715e8b657b10d41d18907468ede2b3c47032378c/src/routes/Team.jsx#L117)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Ayo, my mom has been asking me for ages to get this changed to "Software Lead" and remove the title from Wendi, want to be a homie and do that for me?
</blockquote></details>

lol

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/16)* status: all files reviewed, 2 unresolved discussions (waiting on @KavinSatheeskumar and @Kenttrann2302)

___
*[`src/routes/Team.jsx` line 94 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/16#-NHBUl8o5bCXVPDqmts8:-NHX3IIq5awHO3RVb_So:bj65l4p) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/715e8b657b10d41d18907468ede2b3c47032378c/src/routes/Team.jsx#L94)):*
<details><summary><i>Previously, Carolx715 (Carol Xu) wrote…</i></summary><blockquote>

What do you think should happen instead of that, should the images be centred? 
</blockquote></details>

Yeah, this is the same functionality seen in the original page but it would be nice to fix it up a bit. Either centering the images or widening the gutters between the pictures to make the grid the width of the viewport would both be a good bet

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/16#-:-NQhcmtMCMelds5-DWEc:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @Kenttrann2302 and @QuantumManiac)

**Review by QuantumManiac — APPROVED** [review]
LGTM! This is probably more of a nit, but if we'd like the images on the Teams page to be more consistent with the original site, we should set it such that the images are aligned to the left rather than how they are now. Taking a look at the last row of team members...
Current React Website:
image

Original Website:
image

This also applies to the Almni section. It looks fine either way, so it's up to you.

**Pull request merged**
