### PR TITLE
Implement base functionality and homepage

### PR DESCRIPTION
**Pull request by QuantumManiac**
- Updated README to provide information better relating to this react site specifically
- Implemented the base functionality for the React app, including page routing
- Created the components necessary for and rewrote the site's homepage

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/5)

### CODE REVIEW

**Review by KavinSatheeskumar — APPROVED** [review]
Looks good to me, eh

> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-:-MrcGfPq3KcZRlarOz26:bb2m12a)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @BluCodeGH, @chrissank, @jlsajfj, @NitpreetB, and @wendi-yu)

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
I would consider going with either SASS or CSS modules over plain CSS. There is a good comparison between the styling options available at https://www.freecodecamp.org/news/how-to-style-react-apps-with-css/

> Reviewed 39 of 39 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-:-Mrd_AiG0bEtZCxiWMrg:b-frlbfl)* status: all files reviewed, 5 unresolved discussions (waiting on @chrissank, @jlsajfj, @NitpreetB, @QuantumManiac, and @wendi-yu)

___
*[src/index.css, line 6 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrd_yho33l_mE-QS-MD:-Mrd_yhp59Inf336mnfu:b-fffjvs) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/index.css#L6)):*
> ```CSS
> html, body {
> 	height: 100%;
> 	overflow: auto;
> ```

Best to stick to just spaces or just tabs. Maybe do a search through the codebase and find/replace all tabs?
___
*[src/index.jsx, line 12 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-MrdbG4w-F-jnmqGlzC2:-MrdbG4w-F-jnmqGlzC3:bwc4q5b) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/index.jsx#L12)):*
> ```JavaScript
> import Footer from './components/Footer';
> 
> import 'bootstrap/dist/css/bootstrap.min.css';
> ```

Do we need this with `react-bootstrap`?
___
*[src/components/ImageLink.jsx, line 16 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrdavjl9EHqBWtBtRsd:-Mrdavjl9EHqBWtBtRse:bs0n9pp) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/components/ImageLink.jsx#L16)):*
> ```JavaScript
>       </a>
>       <h1 className="image-link-title">
>         <a href={image}>{title}</a>
> ```

The title should link to the link, not the image?
___
*[src/components/routes/Home.jsx, line 21 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrdbn5BBiep6F04nR0M:-Mrdbn5BBiep6F04nR0N:b-dob3pa) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/components/routes/Home.jsx#L21)):*
> ```JavaScript
>       <Container fluid>
>         <Row className="content-row">
>           <Col md={6}>
> ```

This text is very wide on our current website, can we set a maximum width?
___
*[src/components/routes/index.js, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrdc5HgE1ppFdjZ7qo0:-Mrdc5HgE1ppFdjZ7qo1:b-box6x6) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/components/routes/index.js#L2)):*
> ```JavaScript
> // A list of routes and their names to be used by components that require them
> const routes = [
> ```

This seems very repetitive and navbar-specific (what happens when we want to use a route that isn't in the navbar). I think it would be cleaner to define the navbar pages explicitly in the navbar jsx.

**Review by NitpreetB — APPROVED** [review]
I downloaded a local copy and it worked, so looks go to me

> Reviewed 38 of 39 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-:-MreQXWQ53Ffuk0Qngzr:b-thvkid)* status: all files reviewed, 5 unresolved discussions (waiting on @chrissank, @jlsajfj, @QuantumManiac, and @wendi-yu)

**Review by QuantumManiac — COMMENTED** [review]
Component and route styling switched over to use CSS Modules

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-:-Mrwrdth8rMFIH7i7k5q:br5p50l)* status: 24 of 41 files reviewed, 5 unresolved discussions (waiting on @BluCodeGH, @chrissank, @jlsajfj, @KavinSatheeskumar, @NitpreetB, and @wendi-yu)

___
*[src/index.css, line 6 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrd_yho33l_mE-QS-MD:-MrwnWxJ0JdAfxZJTXbT:b-qqkjl5) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/index.css#L6)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Best to stick to just spaces or just tabs. Maybe do a search through the codebase and find/replace all tabs?
</blockquote></details>

Fixed. Added eslint rule to standardize this, although this doesn't apply to CSS files.
___
*[src/index.jsx, line 12 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-MrdbG4w-F-jnmqGlzC2:-MrwnfkP4c_o5FJVsgZI:b-yyeqwu) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/index.jsx#L12)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Do we need this with `react-bootstrap`?
</blockquote></details>

Yep, required as per [the documentation](https://react-bootstrap.github.io/getting-started/introduction/#stylesheets)
___
*[src/components/ImageLink.jsx, line 16 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrdavjl9EHqBWtBtRsd:-MrwrsIZE9sTJhom1JJd:b-4b5g9p) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/components/ImageLink.jsx#L16)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

The title should link to the link, not the image?
</blockquote></details>

Good catch, fixed
___
*[src/components/routes/Home.jsx, line 21 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrdbn5BBiep6F04nR0M:-Mrwyifl5zQU0oFqhYTJ:bqqezjw) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/components/routes/Home.jsx#L21)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

This text is very wide on our current website, can we set a maximum width?
</blockquote></details>

Made the text a bit less wide by adding a gutter in the middle. Looks a bit odd with the empty space in the middle though. Alternatively, we can make the gutter smaller and move the text in, but that will make the edge of the text not line up with the edge of the images below. Thoughts?
___
*[src/components/routes/index.js, line 2 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrdc5HgE1ppFdjZ7qo0:-MrwtmEAD2gcnIokJP02:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/components/routes/index.js#L2)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

This seems very repetitive and navbar-specific (what happens when we want to use a route that isn't in the navbar). I think it would be cleaner to define the navbar pages explicitly in the navbar jsx.
</blockquote></details>

Done

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/5)* status: all files reviewed, 2 unresolved discussions (waiting on @chrissank, @jlsajfj, @QuantumManiac, and @wendi-yu)

___
*[src/components/routes/Home.jsx, line 21 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrdbn5BBiep6F04nR0M:-Mrx0ny7Bel6Wte3bsy-:b-b6u6bz) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/components/routes/Home.jsx#L21)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Made the text a bit less wide by adding a gutter in the middle. Looks a bit odd with the empty space in the middle though. Alternatively, we can make the gutter smaller and move the text in, but that will make the edge of the text not line up with the edge of the images below. Thoughts?
</blockquote></details>

I'd suggest trying out equal spacing on the left, between them and on the right, or just space on the left and right. The text doesn't perfectly line up on our current website so I wouldn't worry about trying to maintain that. If possible we should only make the space appear on screens over a certain size so it still looks decent on mobile.
___
*[src/components/CoverPhoto.module.css, line 3 at r3](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrx-ejLDd3lCaDBiNQA:-Mrx-ejLDd3lCaDBiNQB:bn0897l) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/fbc1204af681b6da66c3ef12b4f408a8137a4818/src/components/CoverPhoto.module.css#L3)):*
> ```CSS
> .coverPhoto {
>   height: 39rem;
> 	background-repeat: no-repeat;
> ```

You have spaces one line and a tab the next. Even if eslint doesn't fix it automatically we should still be consistent.

**Review by QuantumManiac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/5)* status: 32 of 41 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @chrissank, @jlsajfj, and @wendi-yu)

___
*[src/components/routes/Home.jsx, line 21 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrdbn5BBiep6F04nR0M:-Ms0X28s5aId5nQTujU2:b5rsdq9) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/e16ff799a3fe3b5cfa25dac0d5689f25d707f158/src/components/routes/Home.jsx#L21)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

I'd suggest trying out equal spacing on the left, between them and on the right, or just space on the left and right. The text doesn't perfectly line up on our current website so I wouldn't worry about trying to maintain that. If possible we should only make the space appear on screens over a certain size so it still looks decent on mobile.
</blockquote></details>

Changed, added generous spacing on the left and right, and a bit less on the middle.
___
*[src/components/CoverPhoto.module.css, line 3 at r3](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Mrx-ejLDd3lCaDBiNQA:-Ms0X0KV082FQLgacG17:b-lx4fj3) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/fbc1204af681b6da66c3ef12b4f408a8137a4818/src/components/CoverPhoto.module.css#L3)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

You have spaces one line and a tab the next. Even if eslint doesn't fix it automatically we should still be consistent.
</blockquote></details>

Fixed.

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-:-Ms0wz86D4Z7BVoMr7zr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrissank, @jlsajfj, and @wendi-yu)

**Review by jlsajfj — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/5)* status: all files reviewed, 7 unresolved discussions (waiting on @chrissank, @QuantumManiac, and @wendi-yu)

___
*[src/index.css, line 23 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0iyiz9Yot48Kv72vJ:-Ms0iyiz9Yot48Kv72vK:b-15glje) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/index.css#L23)):*
> ```CSS
>   color: #337ab7;
>   text-decoration: none;  
> }
> ```

general stuff like this shouldnt be used in such a sweeping way, even the `code` block I would argue.

i guess just delete it, or keep the `text-decoration: none;`



_Code quote:_
```CSS
a:hover, a:visited {
  text-decoration: none;
}

a {
  color: #337ab7;
  text-decoration: none;
}
```
___
*[src/components/ImageLink.jsx, line 11 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0lpovC6vKkjB2v36Q:-Ms0lpovC6vKkjB2v36R:b-8ggva4) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/ImageLink.jsx#L11)):*
> ```JavaScript
> }) => {
>   return (
>     <>
> ```

i would make this a div with className={styles.imageLinkBody} just so we can have general styles per block
___
*[src/components/ImageLink.jsx, line 18 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0neC18evJQkDMKsK_:-Ms0neC18evJQkDMKsKa:b65dcop) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/ImageLink.jsx#L18)):*
> ```JavaScript
>         <a href={link}>{title}</a>
>       </h1>
>       <p className={styles.imageLinkText}>{children}</p>
> ```

should this p tag be linked?
___
*[src/components/ImageLink.jsx, line 19 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0lx40Ew3_Qho5BILR:-Ms0lx40Ew3_Qho5BILS:baw5f5n) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/ImageLink.jsx#L19)):*
> ```JavaScript
>       </h1>
>       <p className={styles.imageLinkText}>{children}</p>
>     </>
> ```

this would need to be changed to match comment on line 11 (</div>)
___
*[src/components/ImageLink.jsx, line 23 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0nkFj5-io_4kOhlrJ:-Ms0nkFj5-io_4kOhlrK:b-uavj3q) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/ImageLink.jsx#L23)):*
> ```JavaScript
> };
> 
> export default ImageLink;
> ```

overall, wrap the whole thing with the `a` tag (probably in the div body), however wrapping it in a larger body tag would cause the css to have to be reworked a bit, changes proposed in comment on `ImageLink.module.css`

only widely noticeable effect of wrapping everything in the `a` tag is that the margins of padding on each block are also now clickable.

something like the snippet shown



_Code snippet:_
```JavaScript
    <div className={styles.imageLinkBody}>
      <a href={link}>
        <Image className={styles.imageLinkImage} src={image} alt={`Link: ${title}`} />
      <h1 className={`${styles.imageLinkTitle} pt-3`}>
        {title}
      </h1>
      <p className={styles.imageLinkText}>{children}</p>
      </a>
    </div>
```
___
*[src/components/Footer.module.css, line 4 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0eyDbC_ZzNFmXuWbB:-Ms0eyDbC_ZzNFmXuWbC:b5gcs2b) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/Footer.module.css#L4)):*
> ```CSS
>   height: 5rem;
>   text-align: center;
>   padding-top: 2.3rem;
> ```

From a visual perspective feels a bit too low. Maybe 1.7rem instead.
___
*[src/components/ImageLink.module.css, line 28 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms10mOKCChkptMeDo0w:-Ms10mOKCChkptMeDo0x:bjedz8e) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/ImageLink.module.css#L28)):*
> ```CSS
>   color: grey
> }
> ```

not a blocker but if the whole thing is clickable id propose for the whole thing to have noticable effect when hovered.

shifted the hover from `a:hover` to `imageLinkBody:hover a` and with the change to location of `a` tag in `ImageLink.jsx`,  all the text changes

i put a proposed `transform:scale...` which makes it very clear the picture is clickable too. this could be done better and if included should be redone in another fashion, as scaling produces a bit of noise while it moves



_Code snippet:_
```CSS
.imageLinkImage {
  display:block;
  width: 90%;
  margin: auto;
}

.imageLinkTitle {
  text-align: center;
  font-weight: 500;
  font-size: 1.5rem;
}

.imageLinkTitle {
  margin: 1rem;
}

.imageLinkBody {
  transition: transform 0.3s ease;
}

.imageLinkBody:hover {
  transform: scale(1.005);
}

.imageLinkBody a {
  color: black;
  transition: color 0.3s ease;
}

.imageLinkBody:hover a {
  color: grey
}

.imageLinkText {
  text-align: center;
  line-height: 135%;
  font-weight: 400;
  font-size: 0.9rem;
}
```

**Review by QuantumManiac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/5)* status: 38 of 41 files reviewed, 7 unresolved discussions (waiting on @BluCodeGH, @chrissank, @jlsajfj, and @wendi-yu)

___
*[src/index.css, line 23 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0iyiz9Yot48Kv72vJ:-MsAxPS86l2janVuMH9P:b-jdirjo) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/index.css#L23)):*
<details><summary><i>Previously, jlsajfj wrote…</i></summary><blockquote>

general stuff like this shouldnt be used in such a sweeping way, even the `code` block I would argue.

i guess just delete it, or keep the `text-decoration: none;`
</blockquote></details>

This is copied over from the original site, but I don't see why it would need to  be removed. I don't see any reason as to why there would be different link colors for different pages or something. If some page does need a different color, it wouldn't be too bad to do some styling with higher specificity for that case.
___
*[src/components/ImageLink.jsx, line 11 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0lpovC6vKkjB2v36Q:-MsAyOyyAUZrrmqyQo-2:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/ImageLink.jsx#L11)):*
<details><summary><i>Previously, jlsajfj wrote…</i></summary><blockquote>

i would make this a div with className={styles.imageLinkBody} just so we can have general styles per block
</blockquote></details>

Done.
___
*[src/components/ImageLink.jsx, line 18 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0neC18evJQkDMKsK_:-MsAyU-ZAV2Xd4SBLy4M:b-bgkxja) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/ImageLink.jsx#L18)):*
<details><summary><i>Previously, jlsajfj wrote…</i></summary><blockquote>

should this p tag be linked?
</blockquote></details>

Don't think so. Just the title and picture should be fine imo
___
*[src/components/ImageLink.jsx, line 19 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0lx40Ew3_Qho5BILR:-MsB19yn41YHu1iq5WHc:b32w0x) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/ImageLink.jsx#L19)):*
<details><summary><i>Previously, jlsajfj wrote…</i></summary><blockquote>

this would need to be changed to match comment on line 11 (</div>)
</blockquote></details>

OK
___
*[src/components/ImageLink.jsx, line 23 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0nkFj5-io_4kOhlrJ:-MsB-bb16B5TDmFIM8dC:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/ImageLink.jsx#L23)):*
<details><summary><i>Previously, jlsajfj wrote…</i></summary><blockquote>

overall, wrap the whole thing with the `a` tag (probably in the div body), however wrapping it in a larger body tag would cause the css to have to be reworked a bit, changes proposed in comment on `ImageLink.module.css`

only widely noticeable effect of wrapping everything in the `a` tag is that the margins of padding on each block are also now clickable.

something like the snippet shown
</blockquote></details>

Done.
___
*[src/components/Footer.module.css, line 4 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0eyDbC_ZzNFmXuWbB:-MsAy0nI6Hex-3NDimyR:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/Footer.module.css#L4)):*
<details><summary><i>Previously, jlsajfj wrote…</i></summary><blockquote>

From a visual perspective feels a bit too low. Maybe 1.7rem instead.
</blockquote></details>

Done.
___
*[src/components/ImageLink.module.css, line 28 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms10mOKCChkptMeDo0w:-MsB0tQp-YwP8s86JETy:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/components/ImageLink.module.css#L28)):*
<details><summary><i>Previously, jlsajfj wrote…</i></summary><blockquote>

not a blocker but if the whole thing is clickable id propose for the whole thing to have noticable effect when hovered.

shifted the hover from `a:hover` to `imageLinkBody:hover a` and with the change to location of `a` tag in `ImageLink.jsx`,  all the text changes

i put a proposed `transform:scale...` which makes it very clear the picture is clickable too. this could be done better and if included should be redone in another fashion, as scaling produces a bit of noise while it moves
</blockquote></details>

Done.

**Review by jlsajfj — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/5)* status: all files reviewed, 1 unresolved discussion (waiting on @chrissank, @QuantumManiac, and @wendi-yu)

___
*[src/index.css, line 23 at r4](https://reviewable.io/reviews/waterloo-rocketry/website-react/5#-Ms0iyiz9Yot48Kv72vJ:-MsB1abN4lNlK7-1tj8C:b-t4c3rw) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/94fd707f299d7891bb59e517563062466030d399/src/index.css#L23)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

This is copied over from the original site, but I don't see why it would need to  be removed. I don't see any reason as to why there would be different link colors for different pages or something. If some page does need a different color, it wouldn't be too bad to do some styling with higher specificity for that case.
</blockquote></details>

True, if it works it works

**Pull request merged**
