### PR TITLE
Rockets development

### PR DESCRIPTION
**Pull request by lucasreljic**
- Worked off of SOTS development and added the other rockets. 
- All information was copied from the old website
- Review all info for rockets and confirm it is correct and no error was created when copying
- One video from WRT1 had to be removed because it is no longer public (a youtube issue)

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/22)

### CODE REVIEW

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
looks good so far! Just a few corrections to be made.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/22#-:-NQbOgv92zTaRy4TNhKU:b-5rbysh)* status: all files reviewed, 3 unresolved discussions (waiting on @KavinSatheeskumar and @lucasreljic)

___
*[`src/index.jsx` line 68 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/22#-NQbLlxj1D0aV3CKUol0:-NQbLlxj1D0aV3CKUol1:b-74nt4z) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/a41e65f25e288d201d0ad299dc0bae077466a567/src/index.jsx#L68)):*
> ```JavaScript
>         <Route
>           exact
>           path="/rockets/uxo"
> ```

Now that we have so many rocket pages, we should probably look into the implementation of nested routes in React Router for them so we don't need to have the `path` prop be `/rockets/{rocketName}`. A quick Google search leads to [this article](https://dev.to/tywenk/how-to-use-nested-routes-in-react-router-6-4jhd), which looks promising.
___
*[`src/img/rocketPhotos/eridani_upright.png` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/22#-NQbMSNk1F6OwgsUgeE2:-NQbMSNk1F6OwgsUgeE3:bvdodgr) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/a41e65f25e288d201d0ad299dc0bae077466a567/src/img/rocketPhotos/eridani_upright.png#L0)):*
For all these pictures, their resolutions are absolutely massive for a picture that's so small on the page. I know that this is also an issue on the original page, but could we use this as an opportunity to reduce the resolution of the pictures to save on KBs a bit?
___
*[`src/routes/rocketPages/Vidar2.jsx` line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/22#-NQbNwp77DhcAZwtB1JH:-NQbNwp77DhcAZwtB1JI:b5w9bxv) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/a41e65f25e288d201d0ad299dc0bae077466a567/src/routes/rocketPages/Vidar2.jsx#L29)):*
> ```JavaScript
>           [
>             [{ 'Wet Mass': '70 lbs', 'Dry Mass': '55 lbs' }, { Diameter: '4"', Length: '72"' }, { Fuel: 'Aluminized HTPB', Oxidizer: 'Nitrous Oxide' }],
>             [{ 'Peak Thrust': '430 lbf', 'Average Thrust': '330 lbf' }, { 'Burn Time': '9 s', 'Motor Classification': 'N' }, { 'Drogue Chute': 'Drone', 'Drogue Chute Diameter': '5ft' }, { 'Main Chute Diameter': '8ft' }],
> ```

The spacing here looks a bit off compared to the original page. Also, "Main Chute: Toroidal" seems to be missing

**Review by KavinSatheeskumar — COMMENTED** [review]
Other than Chamath's other comments, I see no issues. 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/22#-:-NQhdWzT-Fm-C0SyKgJ3:b-3h757v)* status: all files reviewed, 3 unresolved discussions (waiting on @lucasreljic)

**Comment by lucasreljic** [comment]
So for nested routes @QuantumManiac do you still want the parent route to be rendered? Because I don't know if you can stop the parent route from rendering and only render the child route.

**Comment by QuantumManiac** [comment]
> So for nested routes @QuantumManiac do you still want the parent route to be rendered? Because I don't know if you can stop the parent route from rendering and only render the child route.

afaik as long as you don't make the `path` for the parent route something like `rockets/*` then when you're on a child route the parent route shouldn't get rendered. The change to `index.jsx` seems to be working properly unless I'm missing something.

**Review by QuantumManiac — APPROVED** [review]
LGTM!

**Comment by lucasreljic** [comment]
> > So for nested routes @QuantumManiac do you still want the parent route to be rendered? Because I don't know if you can stop the parent route from rendering and only render the child route.
> 
> 
> 
> afaik as long as you don't make the `path` for the parent route something like `rockets/*` then when you're on a child route the parent route shouldn't get rendered. The change to `index.jsx` seems to be working properly unless I'm missing something.
> 
> 
> 
> If you mean if the `/rockets` route should be rendered in general, then yes, it should be rendered when we're at the `/rockets` path

If you look at the bottom of each rockets page (for example /uxo) you will see the general /rockets page rendered as well because of how nested routes work. I think the intended use case for nested routes is to have a page within a page where the child is within the parent page.

**Comment by QuantumManiac** [comment]
> If you look at the bottom of each rockets page (for example /uxo) you will see the general /rockets page rendered as well because of how nested routes work. I think the intended use case for nested routes is to have a page within a page where the child is within the parent page.

Oh, interesting! It didn't load when I initially checked it for some reason. 

If that's the case then we might as well revert to the original way that we did our routes.

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/22#-:-NR5hZ2b-r0AQ51RD5wb:bnfp4nl)* status: 6 of 21 files reviewed, 3 unresolved discussions (waiting on @lucasreljic and @QuantumManiac)

**Pull request merged**
