### PR TITLE
Update Documentation.jsx to ignore maxlen errors

### PR DESCRIPTION
**Pull request by Lucifersan**
this commit fixes issue #86

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/87)

### CODE REVIEW

**Review by zangjiucheng — CHANGES_REQUESTED** [review]
Shoule be `{/* eslint-disable max-len */}`?

**Comment by Lucifersan** [comment]
should it? has eslint changed since a couple yrs ago?

**Comment by zangjiucheng** [comment]
I guess so, I got following error: 
```
Line 34:13:  Parsing error: Unexpected token (34:13)
```

Reference: https://eslint.org/docs/latest/rules/max-len#options

**Comment by Lucifersan** [comment]
pls rereview

**Review by zangjiucheng — APPROVED** [review]
LGTM, 🫡 Thanks!

**Pull request merged**
