### PR TITLE
Complete Subsystems Page

### PR DESCRIPTION
**Pull request by QuantumManiac**
Completed the Subsystems page. I had a hard time trying to make a custom component for subsystem description tabs due to how the `Tabs` component interacts with the nested `Tab` components. If anyone has any insight on how this could be made a bit cleaner, please let me know in review!

This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/20)

### CODE REVIEW

**Review by KavinSatheeskumar — COMMENTED** [review]
> Reviewed 76 of 76 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/20)* status: all files reviewed, 2 unresolved discussions (waiting on @Carolx715, @EnviouslyEnvy, and @QuantumManiac)

___
*[`src/routes/Subsystems.jsx` line 54 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/20#-NL9Xje3AMcamJ7g7qaK:-NL9Xje4CYGZMscg6X1c:b-kdiben) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/457b61776dbe171cfb6a3ac6fe73a2df0c948928/src/routes/Subsystems.jsx#L54)):*
> ```JavaScript
>           </Content>
>         </Row>
>         <Row className="my-4 mx-2 gx-5 justify-content-center">
> ```


I personally think this is just a bit too wide, I'd recommend making it a bit smaller. 
___
*[`src/routes/Subsystems.jsx` line 59 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/20#-NL9XvK7AbsEIo2MGLav:-NL9XvK7AbsEIo2MGLaw:b-dd8v4z) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/457b61776dbe171cfb6a3ac6fe73a2df0c948928/src/routes/Subsystems.jsx#L59)):*
> ```JavaScript
>         <Row className="justify-content-md-center mb-4">
>           <Col sm={10} md={8} lg={7}>
>             <Tabs
> ```

I honestly don't really see the issue you were talking about in the comments on this PR, so Imma say /shrug

**Review by QuantumManiac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/20)* status: 75 of 76 files reviewed, 2 unresolved discussions (waiting on @Carolx715, @EnviouslyEnvy, and @KavinSatheeskumar)

___
*[`src/routes/Subsystems.jsx` line 54 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/20#-NL9Xje3AMcamJ7g7qaK:-NLH73mS4BvZa1WMPmMi:bbo3g4o) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/457b61776dbe171cfb6a3ac6fe73a2df0c948928/src/routes/Subsystems.jsx#L54)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>


I personally think this is just a bit too wide, I'd recommend making it a bit smaller. 
</blockquote></details>

Good catch, missed this. Done.
___
*[`src/routes/Subsystems.jsx` line 59 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/20#-NL9XvK7AbsEIo2MGLav:-NLH76HUC7fgARwMmYwK:b-hnmp9l) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/457b61776dbe171cfb6a3ac6fe73a2df0c948928/src/routes/Subsystems.jsx#L59)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

I honestly don't really see the issue you were talking about in the comments on this PR, so Imma say /shrug
</blockquote></details>

Now I realize that it might be a bit too excessive to component-ize the way I had in mind, but basically I wanted to take the `Tab` and `Content` components and combine them together so there's a bit less nesting.

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/20#-:-NOHlmtI1EVBjIdxAwId:bnfp4nl)* status: 75 of 76 files reviewed, all discussions resolved (waiting on @Carolx715 and @EnviouslyEnvy)

**Review by EnviouslyEnvy — APPROVED** [review]
LGTM

**Pull request merged**
