### PR TITLE
Update sponsors page

### PR DESCRIPTION
**Pull request by shirleyfyx**
- Update the sponsors' page based on the chart below. 
- Close https://github.com/waterloo-rocketry/website-react/issues/25

image (5)

image
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/55)

### CODE REVIEW

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Small spelling concerns

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/55#-:-NjUEm-O0FCa3QnmSwLh:bm8g3x7)* status: all files reviewed, 5 unresolved discussions (waiting on @QuantumManiac and @shirleyfyx)

___
*[`src/routes/Sponsors.jsx` line 155 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/55#-NjUCWU86DHWy9phynjf:-NjUCWU86DHWy9phynjg:b-sb8h1l) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/4bb87104530ffcf45ea9923dfcfb7b22a3334a01/src/routes/Sponsors.jsx#L155)):*
> ```JavaScript
>                   is a family-led enterprise. With the addition of their brother Matt, the trio
>                   leads a team of over 50 talented individuals, including professional
>                   administrators, engineers, skilled laborers, and tradesmen. Committed to
> ```

I think we generally follow Canadian/British spellings (i.e labour instead of labor)
___
*[`src/routes/Sponsors.jsx` line 166 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/55#-NjUCmCNBgEJdNauF7WU:-NjUCmCNBgEJdNauF7WV:bb752ax) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/4bb87104530ffcf45ea9923dfcfb7b22a3334a01/src/routes/Sponsors.jsx#L166)):*
> ```JavaScript
>                   their work. As industry leaders, we invest in cutting-edge technologies,
>                   software, machinery, and training to equip employees with the best tools
>                   available. Wel also actively support and sponsors numerous programs that promote
> ```

Typo
___
*[`src/routes/Sponsors.jsx` line 236 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/55#-NjUCzph5k8jpqD1gabQ:-NjUCzph5k8jpqD1gabR:b-7jbqan) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/4bb87104530ffcf45ea9923dfcfb7b22a3334a01/src/routes/Sponsors.jsx#L236)):*
> ```JavaScript
>                   to a global leader in interconnects. Through innovation, advanced technologies,
>                   and exemplary service, Harwin addresses the most demanding connectivity
>                   challenges,empowering customers to gain a competitive edge. Our vision is clear:
> ```

space
___
*[`src/routes/Sponsors.jsx` line 323 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/55#-NjUDRet0PXp0cUBaHl9:-NjUDRet0PXp0cUBaHlA:b-3t1v99) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/4bb87104530ffcf45ea9923dfcfb7b22a3334a01/src/routes/Sponsors.jsx#L323)):*
> ```JavaScript
>                   Recognized as one of the world' most innovative companies, ANSYS has been
>                   dedicated to engineering simulation for over 45 years. We develop and support
>                   simulation software for predicting product designs' real-world behavior.
> ```

See above comment about spelling
___
*[`src/routes/Sponsors.jsx` line 331 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/55#-NjUDiiR4MAqCvAWkgD-:-NjUDiiR4MAqCvAWkgD0:b11znr7) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/4bb87104530ffcf45ea9923dfcfb7b22a3334a01/src/routes/Sponsors.jsx#L331)):*
> ```JavaScript
>                 <p className="content-text">
>                   At DX Engineering, Amateur Radio is what we know. We understand your every need
>                   for top-performing and reliable products, and It's impossible to overstate the
> ```

Unnecessary uppercase

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Looks good! Just one thing regarding the unescaped characters.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/55#-:-Njo27hU9UATMhI3pAcE:b-1mbo1d)* status: all files reviewed, 6 unresolved discussions (waiting on @Darth-Raazi and @shirleyfyx)

___
*[`src/routes/Sponsors.jsx` line 1 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/55#-Njo1cnFDdcShuFyO0Fn:-Njo1cnFDdcShuFyO0Fo:b-wzzosm) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/1b48b925ca20f1eeef14e312c13d1fd6d0699651/src/routes/Sponsors.jsx#L1)):*
> ```JavaScript
> /* eslint-disable react/no-unescaped-entities */
> ```

You should probably not have this here and deal with the unescaped entities instead. My guess is that the issue are the apostrophes, which can be easily resolved by replacing all instances of `'` in the text with `&apos;`

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/55#-:-Njrqyyr9llBLc-m2vCs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @QuantumManiac and @shirleyfyx)

**Review by QuantumManiac — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @shirleyfyx)

**Pull request merged**
