### PR TITLE
General dev

### PR DESCRIPTION
**Pull request by Carolx715**
- Completed Competition page
- Started work on Join page
- modified components in the Home page to be reusable in Competition and Join pages
- restructured/renamed image files according to new naming convention

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/9)

### CODE REVIEW

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> Reviewed 90 of 90 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/9)* status: all files reviewed, 1 unresolved discussion (waiting on @Carolx715 and @QuantumManiac)

___
*[`src/routes/Rockets.jsx` line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCDaQG-8zItvg0BRpaJ:-NCDaQG06d392tdZfnDP:b3a3hph) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/routes/Rockets.jsx#L6)):*
> ```JavaScript
> import Content from '../components/Content/Content';
> 
> const Rockets = () => {
> ```

This page is kinda wack rn, once you fix it, I'll approve the PR

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
LGTM so far! Please address review comments and re-request review.

> Reviewed 90 of 90 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-:-NCNVzwFEcu9fz5yvlJy:b-6fkgwv)* status: all files reviewed, 5 unresolved discussions (waiting on @Carolx715 and @KavinSatheeskumar)

___
*[`src/components/DividerLine/DividerLine.module.css` line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCNU1W3Cbhdh07hG_h4:-NCNU1W3Cbhdh07hG_h5:b-l9pir6) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/components/DividerLine/DividerLine.module.css#L1)):*
> ```CSS
> /* LINE ELEMENT */
> ```

Totally wanted to switch over to CSS modules from whatever we were using that (or did I end up implementing that? idk). Nice!
___
*[`src/routes/Join.jsx` line 53 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCNV40u7pJO4mEByCFu:-NCNV40u7pJO4mEByCFv:b-ukt141) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/routes/Join.jsx#L53)):*
> ```JavaScript
> 
>         <Row className={`my-0 ${styles.faqContainer}`}>
>           <SubsectionTitle title="FREQUENTLY ASKED QUESTIONS" />
> ```

It seems that the FAQ section is incomplete. Is this for a later PR? If so, maybe keep this bit commented out for now.
___
*[`src/routes/Rockets.jsx` line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCDaQG-8zItvg0BRpaJ:-NCNVJqj0dA94jkRdvdu:buzirqa) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/routes/Rockets.jsx#L6)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

This page is kinda wack rn, once you fix it, I'll approve the PR
</blockquote></details>

Page is indeed whack. Issue seems to be that content is going under the navbar which isn't a problem on other pages since we have a cover picture at the top.
___
*[`src/components/CoverPhoto/CoverPhoto.module.css` line 2 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCNTcRd6ZlB8buWD-9N:-NCNTcRd6ZlB8buWD-9O:bwdz35k) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/components/CoverPhoto/CoverPhoto.module.css#L2)):*
> ```CSS
> .coverPhoto {
>   /* height: 39rem; */
> ```

Yeah, I just somewhat-arbitrarily grabbed this from the vanilla website's CSS. Just get rid of it rather than commenting it out tbh
___
*[`src/routes/Home.jsx` line 18 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCNViMo7iiHDgMHPVTv:-NCNViMo7iiHDgMHPVTw:b20nk20) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/routes/Home.jsx#L18)):*
> ```JavaScript
>   return (
>     <>
>       <CoverPhoto image={coverPhotoImage} height="39rem" position="50% 60%" />
> ```

the way the height and position styles are being applied feel slightly odd to me for some reason. Is this usually how it's done through props?

**Review by Carolx715 — COMMENTED** [review]
addressed most of them, had some questions for others

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-:-NCSyf8W3gXvhd-dcspt:b-35a0yy)* status: all files reviewed, 5 unresolved discussions (waiting on @KavinSatheeskumar and @QuantumManiac)

___
*[`src/components/DividerLine/DividerLine.module.css` line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCNU1W3Cbhdh07hG_h4:-NCSykPQ7c67ow-x9LC0:b-8fx2u7) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/components/DividerLine/DividerLine.module.css#L1)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Totally wanted to switch over to CSS modules from whatever we were using that (or did I end up implementing that? idk). Nice!
</blockquote></details>

:+1: 
___
*[`src/routes/Join.jsx` line 53 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCNV40u7pJO4mEByCFu:-NCSyEhECZRN0_OVm8E-:b-k7lgnj) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/routes/Join.jsx#L53)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

It seems that the FAQ section is incomplete. Is this for a later PR? If so, maybe keep this bit commented out for now.
</blockquote></details>

This is incomplete, yes. Can I just comment out the Row for now and leave this page in?
___
*[`src/routes/Rockets.jsx` line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCDaQG-8zItvg0BRpaJ:-NCSyMxHDc2Lnnv3OH1b:b-kv9ma3) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/routes/Rockets.jsx#L6)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Page is indeed whack. Issue seems to be that content is going under the navbar which isn't a problem on other pages since we have a cover picture at the top.
</blockquote></details>

Took this page out of this PR entirely - to continue it I think I would have to define a new component to represent a rectangle with an image and text overlay a la the original website, which will probably make this PR even bigger than it is now, and we should keep this small
___
*[`src/components/CoverPhoto/CoverPhoto.module.css` line 2 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCNTcRd6ZlB8buWD-9N:-NCSxsaP9f5J7L4kb4CR:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/components/CoverPhoto/CoverPhoto.module.css#L2)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Yeah, I just somewhat-arbitrarily grabbed this from the vanilla website's CSS. Just get rid of it rather than commenting it out tbh
</blockquote></details>

Done
___
*[`src/routes/Home.jsx` line 18 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCNViMo7iiHDgMHPVTv:-NCSy21N39gKHut2oUBn:b-82vroe) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/routes/Home.jsx#L18)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

the way the height and position styles are being applied feel slightly odd to me for some reason. Is this usually how it's done through props?
</blockquote></details>

uhhhh... now that you mention it I don't think it is. I don't know how it is typically done in react either. I'll look into this more

**Review by Carolx715 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/9)* status: 83 of 90 files reviewed, 5 unresolved discussions (waiting on @KavinSatheeskumar and @QuantumManiac)

___
*[`src/routes/Home.jsx` line 18 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCNViMo7iiHDgMHPVTv:-NCbv0XdCfMPp44WRcPI:beu8uql) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/routes/Home.jsx#L18)):*
<details><summary><i>Previously, Carolx715 (Carol Xu) wrote…</i></summary><blockquote>

uhhhh... now that you mention it I don't think it is. I don't know how it is typically done in react either. I'll look into this more
</blockquote></details>

I did some research and changed it to the way I saw react-ers usually do it. Let me know if this looks right to you.

**Review by QuantumManiac — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-:-NCgkHFJ3wRCEv1e9Jsd:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Carolx715 and @KavinSatheeskumar)

___
*[`src/routes/Join.jsx` line 53 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCNV40u7pJO4mEByCFu:-NCgkC2J2gofuLWV2eNA:b-5g1u4n) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/47fee1064367bbeb42a036bd3f33e905a022131b/src/routes/Join.jsx#L53)):*
<details><summary><i>Previously, Carolx715 (Carol Xu) wrote…</i></summary><blockquote>

This is incomplete, yes. Can I just comment out the Row for now and leave this page in?
</blockquote></details>

Yeah, I think that should be good.
___
*[`src/components/CoverPhoto/CoverPhoto.jsx` line 8 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-NCgjwATDq7qBtyh70tc:-NCgjwATDq7qBtyh70td:bv5x0yt) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/2a4cd73e13ae33c1a52e6818e18c1788b0c031d1/src/components/CoverPhoto/CoverPhoto.jsx#L8)):*
> ```JavaScript
> const CoverPhoto = ({ image, style }) => {
>   return (
>     <div className={styles.coverPhoto} style={{ backgroundImage: `url(${image})`, ...style }} />
> ```

Yes, totally what I had in mind after I thought about it for a bit. Nice!

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/9#-:-NCgqP7Z15jl3fd8aFlm:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Carolx715)

**Pull request merged**
