### PR TITLE
FAQComponent added, Join page complete

### PR DESCRIPTION
**Pull request by Carolx715**
- Created a component to represent the FAQ Component on the "Join" page 
- Completed the join page

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/11)

### CODE REVIEW

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
There seems to be a bit of a visual issue with the expanding and collapsing on your `FAQComponent` on the join page - when you click the button to expand/collapse, it seems to instantly change the height of the answer text area to around one line height and then smoothly expand/contract in the expected animation.

I suspect the culprit is the `padding: 1%` that you have in the `.answer` CSS due to this note in the [react-bootstrap documentation](https://react-bootstrap.github.io/utilities/transitions/): 
image

I see that you have a `div` as a child of the `FAQComponent` component which is what you put the answer text in. Try applying your padding to that and see if the animation is any smoother.

**Review by Carolx715 — COMMENTED** [review]
I added an additional div in the FAQComponent instead, it is no longer glitchy and is smooth now!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/11#-:-NDtTLAq-7HNy_DS9JMp:b2rzjsr)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @KavinSatheeskumar)

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/11#-:-NDud_jP5T8x_S8L1dnx:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved

**Review by QuantumManiac — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Carolx715)

**Pull request merged**
