### PR TITLE
Add Shark of the Sky page and generic classes to enable future development of rocket pages

### PR DESCRIPTION
**Pull request by KavinSatheeskumar**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/15)

### CODE REVIEW

**Review by Carolx715 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/15)* status: all files reviewed, 2 unresolved discussions (waiting on @KavinSatheeskumar, @Kenttrann2302, and @QuantumManiac)

___
*[`src/components/Gallery/Gallery.jsx` line 63 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NGht-DVDLP-ORq9RGeo:-NGht-DVDLP-ORq9RGep:bmtx2qp) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/components/Gallery/Gallery.jsx#L63)):*
> ```JavaScript
> };
> 
> export { Photo, Video, Gallery };
> ```

pog i like this file it's just satisfying
___
*[`src/components/SpecsComponent/SpecsComponent.jsx` line 47 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NGhuVyN0pCiCDmShI7r:-NGhuVyN0pCiCDmShI7s:bibhdqh) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/components/SpecsComponent/SpecsComponent.jsx#L47)):*
> ```JavaScript
> /* eslint-enable */
> 
> const SpecsComponent = ({ specs }) => {
> ```




I am not sure what you were going for, were the items in each groupElems supposed to be on separate lines? See my attached images, but it looks like some of them are showing up on the same line as opposed to on separate lines (like Diameter and Length). 
___
*[`src/components/SpecsComponent/SpecsComponent.jsx` line 78 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NGhvPxq-ADjwX8rrCXp:-NGhvPxq-ADjwX8rrCXq:b-gpl6yi) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/components/SpecsComponent/SpecsComponent.jsx#L78)):*
> ```JavaScript
> };
> 
> export default SpecsComponent;
> ```

This is also just a very satisfying file
___
*[`src/routes/rocketPages/SharkOfTheSky.jsx` line 34 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NGhwFfdESbANC71mRI2:-NGhwFfdESbANC71mRI3:bkq9n6x) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/routes/rocketPages/SharkOfTheSky.jsx#L34)):*
> ```JavaScript
>         <TwoColumns title="DETAILS">
>           <>
>             <Content title="PAYLOAD">
> ```

I was thinking, upon loading this page, it would be better to add a bit of a top margin to the <Content /> element. The paragraph sections look a little too close together on this page

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/15)* status: all files reviewed, 5 unresolved discussions (waiting on @Carolx715, @KavinSatheeskumar, and @Kenttrann2302)

___
*[`.eslintrc.json` line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NHX53j58TbqXPRlFoFM:-NHX53j58TbqXPRlFoFN:bab3e5b) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/.eslintrc.json#L29)):*
> ```jsonc
>         "max-len": 1,
>         "indent": ["error", 2],
>         "max-classes-per-file": 0
> ```

ugh, fine
___
*[`src/components/Gallery/Gallery.module.css` line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NHX4f5s4iONUvuBFFo4:-NHX4f5s4iONUvuBFFo5:b45ct1r) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/components/Gallery/Gallery.module.css#L22)):*
> ```CSS
> 
> .morebutton {
> 	background-color: #8c0733;
> ```

odd color to pick imo, considering that it doesn't really fit the scheme for the rest of the site and/or Waterloo Rocketry. 
___
*[`src/components/Gallery/Gallery.module.css` line 37 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NHX4nfKAgyOXNWFUfV-:-NHX4nfKAgyOXNWFUfV0:b-t7wqbh) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/components/Gallery/Gallery.module.css#L37)):*
> ```CSS
> 
> .morebutton:hover  {
>     background-color: #620423;
> ```

Same "odd color" remark
___
*[`src/components/SpecsComponent/SpecsComponent.jsx` line 47 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NGhuVyN0pCiCDmShI7r:-NHX4zCS1mW_lvog6sNt:b-5uzjcy) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/components/SpecsComponent/SpecsComponent.jsx#L47)):*
<details><summary><i>Previously, Carolx715 (Carol Xu) wrote…</i></summary><blockquote>




I am not sure what you were going for, were the items in each groupElems supposed to be on separate lines? See my attached images, but it looks like some of them are showing up on the same line as opposed to on separate lines (like Diameter and Length). 
</blockquote></details>

I'm seeing the same.
___
*[`src/routes/rocketPages/SharkOfTheSky.jsx` line 34 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NGhwFfdESbANC71mRI2:-NHX58WE0QC-dI0gYFOU:b-pbdqz3) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/routes/rocketPages/SharkOfTheSky.jsx#L34)):*
<details><summary><i>Previously, Carolx715 (Carol Xu) wrote…</i></summary><blockquote>

I was thinking, upon loading this page, it would be better to add a bit of a top margin to the <Content /> element. The paragraph sections look a little too close together on this page


</blockquote></details>

Agreed.

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/15)* status: all files reviewed, 5 unresolved discussions (waiting on @Carolx715, @Kenttrann2302, and @QuantumManiac)

___
*[`src/components/Gallery/Gallery.module.css` line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NHX4f5s4iONUvuBFFo4:-NK0rPq712ne48o8-3lx:b1q4etr) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/components/Gallery/Gallery.module.css#L22)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

odd color to pick imo, considering that it doesn't really fit the scheme for the rest of the site and/or Waterloo Rocketry. 
</blockquote></details>

I just copied this from the old website
___
*[`src/components/Gallery/Gallery.module.css` line 37 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NHX4nfKAgyOXNWFUfV-:-NK0rSN1AWyzdroYrxmK:b5mln06) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/components/Gallery/Gallery.module.css#L37)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Same "odd color" remark
</blockquote></details>

Same response

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/15)* status: all files reviewed, 6 unresolved discussions (waiting on @Carolx715, @KavinSatheeskumar, and @Kenttrann2302)

___
*[`src/index.jsx` line 51 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NOausi-1LqLFds5rn3r:-NOausi-1LqLFds5rn3s:bu46lnw) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/index.jsx#L51)):*
> ```JavaScript
>         <Route
>           exact
>           path="/sots"
> ```

Is there any reason as to why the rocket pages are a top level path? It might make more sense to have it under `rockets` i.e. `rockets/sots`

And no, "I just copied this from the old website" is not a valid answer :P
___
*[`src/components/Gallery/Gallery.module.css` line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NHX4f5s4iONUvuBFFo4:-NOavLYv6RgQorIWX9uW:bo1yx76) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/components/Gallery/Gallery.module.css#L22)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

I just copied this from the old website
</blockquote></details>

We have the freedom to change this. Would there be a more fitting color?
___
*[`src/components/Gallery/Gallery.module.css` line 37 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NHX4nfKAgyOXNWFUfV-:-NOavVbuElohM5m0i1Od:b846ggs) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/components/Gallery/Gallery.module.css#L37)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Same response
</blockquote></details>

Same response to response
___
*[`src/routes/rocketPages/SharkOfTheSky.jsx` line 34 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-NGhwFfdESbANC71mRI2:-NOavlS_Ad54rHY0t-1R:byuawom) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0fea2f6d808ff168e0d8f4398cdb774762127cd0/src/routes/rocketPages/SharkOfTheSky.jsx#L34)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

Agreed.
</blockquote></details>


I feel that the spacing above and below the heading shouldn't be the same. Either increase the space above or reduce it below?

**Review by QuantumManiac — APPROVED** [review]
LGTM! When you're fixing your merge conflicts, make sure to modify this branch's modifications to `index.jsx` to be in the same style as what's found in `master`. No idea why we were using one `Routes` tag for each `Route` tag rather than nesting all the `Route` tags inside of one `Routes` tag.

**Review by KavinSatheeskumar — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/15#-:-NPyhTWS9prBVjZksVOF:bnfp4nl)* status: 6 of 15 files reviewed, 6 unresolved discussions (waiting on @Carolx715 and @Kenttrann2302)

**Review by Carolx715 — APPROVED** [review]
lgtm :tm:

**Pull request merged**
