### PR TITLE
Update Member List

### PR DESCRIPTION
**Pull request by Redstone-ray**
## Description

1. We need our in person safety captain on the page.
2. Quick title update to reflect the most airframe leadership change

## Developer Testing

The changes successfully deploys locally

## Note
What do we want to do with the members who are no longer active on the team (i,e slack deactivated?)?

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/63)

### CODE REVIEW

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/63#-:-NpBOBJn2CgZs2Qe9C25:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @QuantumManiac, @Redstone-ray, and @shirleyfyx)

___
*[`.gitignore` line 135 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/63#-NpBO2dL5jI5wCN-1uyV:-NpBO2dL5jI5wCN-1uyW:b-rt6go4) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/df74da335e55351ff557411861673fdcbf3d8dc4/.gitignore#L135)):*
> ```ignore
> # Misc
> .DS_Store
> .vscode/settings.json
> ```

Ignore the entire `.vscode/` folder please

**Review by Redstone-ray — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/63)* status: 1 of 24 files reviewed, 1 unresolved discussion (waiting on @Darth-Raazi, @QuantumManiac, and @shirleyfyx)

___
*[`.gitignore` line 135 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/63#-NpBO2dL5jI5wCN-1uyV:-Npqof9L9TuO5mvQXDRn:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/df74da335e55351ff557411861673fdcbf3d8dc4/.gitignore#L135)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Ignore the entire `.vscode/` folder please
</blockquote></details>

Done.

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Good to go once you get a few typos taken care of! For typo'd variables, be sure to rename all references to it (I'm too lazy to add comments to them all)

> Reviewed 3 of 3 files at r1, 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/63#-:-Nptw05J-7_Ob1dRq4pz:bqrbrhy)* status: all files reviewed, 4 unresolved discussions (waiting on @Darth-Raazi, @Redstone-ray, and @shirleyfyx)

___
*[`.vscode/settings.json` line 0 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/63#-NptvV6MDuV-FQ8QPnx3:-NptvV6N7OlTilpijnXP:bklz2w5) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/3b0f68c1e1545e92890d3c44b47c4d96c9198e32/.vscode/settings.json#L0)):*
In addition to .gitignoring the .vscode file, please delete the one that's already committed. Since it's gitignored, the easiest way would probably be to delete it through the GitHub site
___
*[`src/routes/Team.jsx` line 30 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/63#-NptvpG48R4lOi8RqS76:-NptvpG48R4lOi8RqS77:bb752ax) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/3b0f68c1e1545e92890d3c44b47c4d96c9198e32/src/routes/Team.jsx#L30)):*
> ```JavaScript
> import JasonX from '../img/teams/jasonX.jpg';
> import JenniferL from '../img/teams/jenniferL.jpg';
> import JermeyS from '../img/teams/jeremyS.jpg';
> ```

Typo



_Suggestion:_
```JavaScript
import JeremyS from '../img/teams/jeremyS.jpg';
```
___
*[`src/routes/Team.jsx` line 172 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/63#-Nptwi8t48Cxa7N6ADBr:-Nptwi8t48Cxa7N6ADBs:b-z2xtph) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/3b0f68c1e1545e92890d3c44b47c4d96c9198e32/src/routes/Team.jsx#L172)):*
> ```JavaScript
>           <MemberImage image={SeanG} name="Sean Gauthier " title="Airframe" />
>           <MemberImage image={ManavT} name="Manav Toor" title="Co-op" />
>           <MemberImage image={YuranW} name="Yu ran Wang" title="Propulsion" />
> ```

Typo. 



_Suggestion:_
```JavaScript
          <MemberImage image={YuRanW} name="Yu Ran Wang" title="Propulsion" />
```

**Comment by Redstone-ray** [comment]
*[`.vscode/settings.json` line  at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/63#-NptvV6MDuV-FQ8QPnx3:-NpuADvdCvv9DhSlxtUY:b-896fix) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/3b0f68c1e1545e92890d3c44b47c4d96c9198e32/.vscode/settings.json#L)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

In addition to .gitignoring the .vscode file, please delete the one that's already committed. Since it's gitignored, the easiest way would probably be to delete it through the GitHub site
</blockquote></details>

Done.

**Review by QuantumManiac — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/63)* status: all files reviewed, 1 unresolved discussion (waiting on @Darth-Raazi and @shirleyfyx)

**Pull request merged**
