### PR TITLE
Contact page

### PR DESCRIPTION
**Pull request by lucasreljic**
I created a contact page with the same layout as the original HTML contact page. As far as I am aware, it is responsive and works across all screen sizes. I noticed the mobile view of the map was too small in the original HTML website so I changed it to have a dynamic height-to-width ratio at smaller screen sizes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/26)

### CODE REVIEW

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
See comments. Should be good to go once addressed!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/26#-:-NbMT1c_3eGl8Yni2v1X:bvvnxz3)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @EnviouslyEnvy, @KavinSatheeskumar, and @lucasreljic)

___
*[`src/img/contact.jpg` line 0 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/26#-NbMQEYu1osDYOnKInn1:-NbMQEYu1osDYOnKInn2:b-chhcxo) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/61349a24486eb172d2556d2195d59b061a28d421/src/img/contact.jpg#L0)):*
1.39MB is pretty large for this picture. Would be good to [compress it a bit](https://imagecompressor.com/)
___
*[`src/routes/Contact.jsx` line 14 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/26#-NbMSPME0gnzCWposnL_:-NbMSPME0gnzCWposnLa:bmnziel) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/61349a24486eb172d2556d2195d59b061a28d421/src/routes/Contact.jsx#L14)):*
> ```JavaScript
> import IgIcon from '../img/instagram-logo.png';
> 
> /* eslint-disable max-len */
> ```

I'm guessing this is for the really long links? Might be good to instead have a `/* eslint-disable-next-line max-len */` right above the offending lines

**Review by QuantumManiac — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/26)* status: all files reviewed, 2 unresolved discussions (waiting on @EnviouslyEnvy, @KavinSatheeskumar, and @lucasreljic)

**Review by QuantumManiac — APPROVED** [review]
:lgtm:, good to go once we get at least one other approval, I reckon

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/26#-:-Nbf6fzC6h5VlsOlIByV:btxbinc)* status: all files reviewed, 2 unresolved discussions (waiting on @EnviouslyEnvy, @KavinSatheeskumar, and @lucasreljic)

**Review by EnviouslyEnvy — APPROVED** [review]
Don't see anything that needs changing, LGTM.

**Pull request merged**
