### PR TITLE
add all teams images

### PR DESCRIPTION
**Pull request by Carolx715**
Just copied all the old mugshots of the team members over into react website

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/13)

### CODE REVIEW

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
All these team member pics are starting to take a chonky bit of space (15MiB worth of images on a single page load is quite a bit). It would be good to run them through an image minifier (e.g. https://imagecompressor.com/) and/or take the PNG files and convert them to JPG

**Review by Carolx715 — COMMENTED** [review]
Agree... maybe it would also be better to have them uploaded to staticflickr, like the rockets? It might help with the size of the repository, though probably not with loading speed. Maybe we should both compress and upload?

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/13#-:-NEs9b_88iU2Lp7hdGv7:b-jr3v4i)* status: 0 of 62 files reviewed, all discussions resolved (waiting on @KavinSatheeskumar and @Kenttrann2302)

**Review by QuantumManiac — COMMENTED** [review]
I think just compressing should be good enough. It should be small enough for the repo afterwards anyway

> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/13#-:-NFZJIa_8ItuR3xbjeP_:brpedjx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KavinSatheeskumar and @Kenttrann2302)

**Review by KavinSatheeskumar — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Kenttrann2302)

**Review by QuantumManiac — APPROVED** [review]

**Pull request merged**
