### PR TITLE
finish top half of the sponsorship page

### PR DESCRIPTION
**Pull request by Kenttrann2302**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/10)

### CODE REVIEW

**Review by Carolx715 — CHANGES_REQUESTED** [review]
Pretty good, just a few minor things I saw!

**Review by Carolx715 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/10#-:-NDub12S4B6hCBBIYeoR:bnfp4nl)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @KavinSatheeskumar and @QuantumManiac)

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/10#-:-NDupgt11qmG3Va7sKOT:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @QuantumManiac)

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Just one comment. Otherwise, LGTM

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/10#-:-NDwjTb6DyuHlmoXjE7t:b-8nmf0s)* status: all files reviewed, 1 unresolved discussion (waiting on @Kenttrann2302)

___
*[`src/index.jsx` line 16 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/10#-NDwj97MBV5oRyJPkQ7I:-NDwj97NA4gZkCegNoBv:b-z0it76) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/483c96295f783aff1786bf4a7484482c80fd2ad2/src/index.jsx#L16)):*
> ```JavaScript
> 
> import Rockets from './routes/Rockets';
> // eslint-disable-next-line import/no-named-as-default
> ```

Any reason why we have this here?

**Review by QuantumManiac — APPROVED** [review]
Not a blocking comment. Whoops.

**Pull request merged**
