### PR TITLE
Outreach page

### PR DESCRIPTION
**Pull request by EnviouslyEnvy**
- Added photos from original site, denoised and upscaled Rocketry Education Session photo to better suit the scale.
- Using ImageBox component for photos.
- Vidar III hyperlink points to its current [non-react page](https://www.waterloorocketry.com/vidar3) as placeholder.
- Feel free to suggest anything.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/19)

### CODE REVIEW

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
It seems that the layout for the sections on the Outreach page are slightly different between the React and original site on smaller viewport widths, with the original site having the text and pictures as columns rather than rows. Take a look at the picture below - left is React site, right is original:
image
If we want to keep things like the original site, changing this might be good. Alternatively, I wouldn't mind the layout on the left if we tweaked it a bit to make the pictures not too large. Thoughts?

**Review by QuantumManiac — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/19#-:-NN9Cbjk5itE9-erzrhl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Carolx715 and @KavinSatheeskumar)

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/19#-:-NNFEWXA-Vt4YMzzPMsA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Carolx715)

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/19#-:-NNFE_aZErKZIo9fzHn7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Carolx715)

**Pull request merged**
