### PR TITLE
Rocket page

### PR DESCRIPTION
**Pull request by Kenttrann2302**
Change rocket cards for rocket page

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/14)

### CODE REVIEW

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/14)* status: 10 of 12 files reviewed, 5 unresolved discussions (waiting on @Kenttrann2302)

___
*[`src/img/rocket/shark-of-the-skye.jpg` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/14#-NFZMaNV6Yc_Bao9E7si:-NFZMaNV6Yc_Bao9E7sj:b-rbsec7) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0b29a49b9d7cfd4f49b37f44d8cfcae81ca8b585/src/img/rocket/shark-of-the-skye.jpg#L0)):*
4MB is massive. Pls compress. Also, typo on file name?
___
*[`src/img/rocket/unexploded-ordnance-2018.jpg` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/14#-NFZMfCb-ThqSk2-TczA:-NFZMfCcANeZxqf8JZF3:b-4npzl5) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0b29a49b9d7cfd4f49b37f44d8cfcae81ca8b585/src/img/rocket/unexploded-ordnance-2018.jpg#L0)):*
3.32MB is massive. Pls compress.
___
*[`src/routes/Rockets.jsx` line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/14#-NFZNqhq1s2hXno065dT:-NFZNqhq1s2hXno065dU:b-4bo6hh) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0b29a49b9d7cfd4f49b37f44d8cfcae81ca8b585/src/routes/Rockets.jsx#L17)):*
> ```JavaScript
>     <div className="page-wrap">
>       <div className={styles.flex__wrapper}>
>         <div className={styles.box}>
> ```

Should move this div into the `RocketCard` component if it's on every single one. Additionally, with the current styling that you've got, the rocket cards don't stretch/squeeze to fit the width of the window when it's resized. This functionality is attributed to the `col-md-4` class in the divs wrapping the rocket cards in the original website

See if you can implement that here.
___
*[`src/routes/Rockets.jsx` line 23 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/14#-NFZMxew7T4vo63khfnh:-NFZMxew7T4vo63khfni:bfjskew) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0b29a49b9d7cfd4f49b37f44d8cfcae81ca8b585/src/routes/Rockets.jsx#L23)):*
> ```JavaScript
>             date="2019"
>             style={{
>               backgroundImage: `url(${rocketCardImage})`,
> ```

You should probably change the `RocketCard` component to pass the `rocketCardImage` as a prop rather than change it in the styles here.
___
*[`src/routes/Rockets.jsx` line 24 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/14#-NFZN6u_4lZDFMtoPu4y:-NFZN6u_4lZDFMtoPu4z:b-j83d1i) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/0b29a49b9d7cfd4f49b37f44d8cfcae81ca8b585/src/routes/Rockets.jsx#L24)):*
> ```JavaScript
>             style={{
>               backgroundImage: `url(${rocketCardImage})`,
>               backgroundSize: 'cover',
> ```

if `backgroundSize` and `backgroundPosition` are the same for all the rocket cards, you should move them into the CSS for the component

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Other than the remaining comments from myself about moving some lines of `RocketCard` into the CSS file and passing the image URL as a prop, looks mostly good!

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/14#-:-NNYAkUp6irQhmteUQCi:b-j6wfsl)* status: all files reviewed, 4 unresolved discussions (waiting on @EnviouslyEnvy, @KavinSatheeskumar, and @Kenttrann2302)

___
*[`src/routes/Rockets.jsx` line 21 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/14#-NNYBC0mA1Uj1kS1Nm9F:-NNYBC0mA1Uj1kS1Nm9G:b9u2rog) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/4dfae4aa729005a6930c94e0d5f25663296d63d6/src/routes/Rockets.jsx#L21)):*
> ```JavaScript
>           <Col>
>             <RocketCard
>               url="https://shark-of-the-sky.com"
> ```

It might be good to change the URLs of the rocket cards into what we would expect them to be once those rocket pages are implemented rather than these temporary fake URLs, so we won't need to come back and change them later. Not too much of an issue though.

**Review by EnviouslyEnvy — APPROVED** [review]
LGTM!

**Review by QuantumManiac — APPROVED** [review]
LGTM!

**Pull request merged**
