### PR TITLE
Competition page creation 

### PR DESCRIPTION
**Pull request by NitpreetB**
Updated the Competition page. instead of the way the link to the competition page is just a "click here" hyperlink on our current website, I added an image link similar to the homepage, as I think that would make the UI more uniform. also, I made the content font size larger.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/8)

### CODE REVIEW

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
Over all very good, only things I have to say are very minor style changes, its a very well written piece of code :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/8#-:-Mtn4KEe7m9rtJuDCymv:b-me61wg)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @addison-ch, @jlsajfj, @NitpreetB, @QuantumManiac, @wendi-yu, and @willerf)

___
*[src/components/routes/competition.jsx, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/8#-Mtn2Za65Z9pXfZDtrqo:-Mtn2Za7EphJnVfQSiVD:btf8ffz) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/f765378a10204edb5fa071827f7deedd236406e8/src/components/routes/competition.jsx#L8)):*
> ```JavaScript
> import ImageLink from '../ImageLink';
> 
> import styles from './Home.module.css';
> ```

If you (and presumably many others) are going to use that bit of CSS, it might be worth renaming and possibly moving up a folder
___
*[src/components/routes/competition.jsx, line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/8#-Mtn4Apb6yJXqGQpyLdK:-Mtn4Apc90BOPyZw7JJb:bja0g4v) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/f765378a10204edb5fa071827f7deedd236406e8/src/components/routes/competition.jsx#L20)):*
> ```JavaScript
>         <Row className={`${styles.imageLinkRow} px-md-5 py-4`}>
>           <Col md={4}>
>             <ImageLink title="Visit the official competition page" image={spacegroupCoverImage} link="https://www.soundingrocket.org/"> </ImageLink>
> ```

Can we make this image a little larger?
___
*[src/components/routes/competition.jsx, line 23 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/8#-Mtn4Dcw6AN05cb52fUR:-Mtn4Dcw6AN05cb52fUS:b24tqd) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/f765378a10204edb5fa071827f7deedd236406e8/src/components/routes/competition.jsx#L23)):*
> ```JavaScript
>           </Col>
>           <Col md={8}>
>             <Content title="INTERCOLLEGIATE ROCKET ENGINEERING COMPETITION">
> ```

Similarly, can we make this text a bit smaller?

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/8)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @addison-ch, @jlsajfj, @KavinSatheeskumar, @NitpreetB, @wendi-yu, and @willerf)

___
*[src/components/LargeContent.jsx, line 6 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/8#-MtogQWk9XyE_K5-_Ibm:-MtogQWk9XyE_K5-_Ibn:broyhxo) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d0811e49b0f73b0cff0b56488967c1ed65546a8/src/components/LargeContent.jsx#L6)):*
> ```JavaScript
> 
> // Text content with a title at the top
> const Content = ({ title, children }) => {
> ```

Standard practice is that the name of the component matches the component's filename. This is especially a big issue here, considering that we already have a `Content` component. Would be good to change this to `LargeContent`.
___
*[src/components/routes/competition.jsx, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/8#-Mtn2Za65Z9pXfZDtrqo:-Mtoguq_3MV_7GtOlmrK:bw5d1k2) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/f765378a10204edb5fa071827f7deedd236406e8/src/components/routes/competition.jsx#L8)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

If you (and presumably many others) are going to use that bit of CSS, it might be worth renaming and possibly moving up a folder
</blockquote></details>

Alternatively, create a `Competition.module.css` with the CSS you need and import that instead
___
*[src/components/routes/competition.jsx, line 1 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/8#-MtoibN19OfNuM4mnywl:-MtoibN19OfNuM4mnywm:b-3e9g5v) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d0811e49b0f73b0cff0b56488967c1ed65546a8/src/components/routes/competition.jsx#L1)):*
> ```JavaScript
> import { React } from 'react';
> ```

Standard practice is that the names for component JSX files start with a capital. Would be good to rename `competition.jsx` to `Competition.jsx`
___
*[src/components/routes/competition.jsx, line 32 at r2](https://reviewable.io/reviews/waterloo-rocketry/website-react/8#-MtohWNB3DhJuNqdJv-r:-MtohWNB3DhJuNqdJv-s:bpjj04r) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/8d0811e49b0f73b0cff0b56488967c1ed65546a8/src/components/routes/competition.jsx#L32)):*
> ```JavaScript
>               rocket&apos;s myriad systems themselves: everything from propulsion and structures to
>               avionics, recovery, and payload. Overuse of commercial components is discouraged.
>               In this way, the IREC promotes student design and a spirit of simple,holistic design:
> ```

space after the comma.



_Code quote:_
```JavaScript
simple,holistic design
```

**Review by aidenfoxivey — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/8)* status: all files reviewed, 8 unresolved discussions (waiting on @addison-ch, @jlsajfj, @KavinSatheeskumar, @NitpreetB, @wendi-yu, and @willerf)

___
*[src/components/routes/competition.jsx, line 23 at r3](https://reviewable.io/reviews/waterloo-rocketry/website-react/8#-N-JfR6v3ecSO70R3rK3:-N-JfR6v3ecSO70R3rK4:b-3nc7d6) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/309a035c07a355bacbc014bf9bc050de50b6dc0d/src/components/routes/competition.jsx#L23)):*
> ```JavaScript
>           </Col>
>           <Col md={8}>
>             <Content title="INTERCOLLEGIATE ROCKET ENGINEERING COMPETITION">
> ```

Is it standard practice for this to be in shouting case?
___
*[src/components/routes/competition.jsx, line 33 at r3](https://reviewable.io/reviews/waterloo-rocketry/website-react/8#-N-Jfjyi4HE9jQy6OMn6:-N-Jfjyi4HE9jQy6OMn7:b-qhucok) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/309a035c07a355bacbc014bf9bc050de50b6dc0d/src/components/routes/competition.jsx#L33)):*
> ```JavaScript
>               avionics, recovery, and payload. Overuse of commercial components is discouraged.
>               In this way, the IREC promotes student design and a spirit of simple,holistic design:
>               excess complexity is the bane of the student rocket engineering team.
> ```

Probably best to go from "simple, holistic design: excess complexity is the bane of student rocket engineering team" to "simple design, as excess complexity is the bane of any student engineering team" to (somewhat ironically) cut down on unnecessary complexity.

**Comment by wendi-yu** [comment]
Task linked: [CU-1vkhg92 Rewrite Competition Page](https://app.clickup.com/t/1vkhg92)

**Pull request closed without merging**
