### PR TITLE
Completed task of adding silver sponsor links

### PR DESCRIPTION
**Pull request by EnviouslyEnvy**
Completed task of adding silver sponsor links.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/17)

### CODE REVIEW

**Review by Carolx715 — APPROVED** [review]
awesomesauceness :) 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/17#-:-NJveOK1-htfGTzdIrSk:bzii903)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @EnviouslyEnvy, @KavinSatheeskumar, and @QuantumManiac)

___
*[`src/routes/Sponsors.jsx` line 316 at r1](https://reviewable.io/reviews/waterloo-rocketry/website-react/17#-NJve61z4KSttnsIDfBq:-NJve61z4KSttnsIDfBr:bjuz0mg) ([raw file](https://github.com/waterloo-rocketry/website-react/blob/4b310aa8fd49503d9040809b6c39b7aeb1c14418/src/routes/Sponsors.jsx#L316)):*
> ```JavaScript
>           </Row>
> 
>           {/* Bronze Sponsors */}
> ```

Whoops this was totally my mistake, Bronze Sponsors should start on line 338. Can you actually move this comment to right before that line for me? Thanks

**Review by QuantumManiac — APPROVED** [review]
LGTM!

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/17#-:-NOHmOpmDC6j7jATbqbg:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Carolx715 and @EnviouslyEnvy)

**Comment by Carolx715** [comment]
:lgtm:

**Review by Carolx715 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/website-react/17#-:-NOHr4Sp18fQ5vZVDAz-:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
